apiVersion: apps/v1
kind: Deployment
metadata:
  name: loanscore
  labels:
    app: loanscore
spec:
  selector:
    matchLabels:
      app: loanscore
  # 34
  replicas: 1
  template:
    metadata:
      labels:
        app: loanscore
    spec:
      containers:
        - name: loanscore
          image: ghcr.io/pierre-yves-monnet/c8-automate-test:latest
          # must be set to always: then any kubectl apply will reload the latest image
          imagePullPolicy: Always
          env:
            - name: JAVA_TOOL_OPTIONS
              value: >-
                -Dcamunda.client.zeebe.grpc-address=http://camunda-zeebe-gateway:26500
                -Dautomator.startup.logLevel=MAIN
